version: '3.7'

services:
  api:
    build: 
      context: ./Backend
    ports: 
      - 9001:9001
    command: ["npm", "run", "start"]
  frontend-auth:
    build: 
      context: ./Frontend/login
    ports: 
      - 8081:8081
    container_name: frontend-auth
    command: ["npm", "run", "serve"]